# Generated by Django 5.1.7 on 2025-03-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edMitra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
